# SPDX-FileCopyrightText: 2024-2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT
name: Main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: 0 0 * * 6
  workflow_dispatch:
jobs:
  check:
    strategy:
      matrix:
        image:
          - macos-14
          - ubuntu-24.04
          - windows-2022
      fail-fast: false
    runs-on: ${{ matrix.image }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - name: Check out the sources
        uses: actions/checkout@v5
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: NuGet cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.fsproj') }}
          path: ${{ env.NUGET_PACKAGES }}
      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --logger trx
        timeout-minutes: 10
      - if: always()
        name: Upload test results
        uses: actions/upload-artifact@v5
        with:
          name: test-results.${{ runner.os }}
          path: '**/TestResults/**'

  licenses:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v5
      - name: REUSE license check
        uses: fsfe/reuse-action@v6

  encoding:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v5
      - name: Verify encoding
        shell: pwsh
        run: scripts/Test-Encoding.ps1
